version: '3.8'

services:
  calendarapi:
    image: amirbakhtiary/calendarendpointswebapi:latest
    ports:
      - "9080:80"
      - "9083:443"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
    - "1833:1433"
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped