version: '3.4'

services:
  calendarapi:
    image: amirbakhtiary/calnedarendpointsapi
    ports:
      - "9080:80"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
    - "1833:1433"